    version: '2'
    services:
       
        ##
        #  PHP-FPM
        ##
        php_fpm:
            build: ./php-fpm/
            volumes:
                - ./php-fpm/supervisor:/etc/supervisor/conf.d
                - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            volumes_from: 
               - source 
            links: 
                - maildev
                - mariadb
                - redis
            expose:
                - 9000
        
        ##
        #  NGINX
        ##
        nginx:
            build: ./nginx/
            volumes:
                - ./nginx/config:/etc/nginx/conf.d
            volumes_from: 
               - source 
            links:
                - php_fpm
            ports:
                - 8080:80
        
        ##
        #  Dev Email
        ##
        maildev:
            image: djfarrelly/maildev
            ports:
                - "8081:80"

        ##
        #  Mysql
        ##
        mariadb:
          image: mariadb
          ports:
            - "3306:3306"
          environment: 
            - MYSQL_ROOT_PASSWORD=password

        phpmyadmin:
          image: phpmyadmin/phpmyadmin
          restart: always
          links:
            - mariadb:db
          ports:
            - "8082:80"
          environment:
            - PMA_USER=root
            - PMA_PASSWORD=password
            - PHP_UPLOAD_MAX_FILESIZE=100MB
 
        ##
        #  Source Containers
        ##
        redis:
            build: ./redis/
            expose:
                - 6379
            ports:
                - 6379:6379

        ##
        #  Source Containers
        ##
        source:
            image: nginx:stable
            volumes:
                - ./source/kronosaurus:/var/www/html
            command: "true"