    version: '2'
    services:
       
        ##
        #  PHP-FPM
        ##
        kronosaurus_php_fpm:
            build: ./php-fpm/
            volumes_from: 
               - source_kronosaurus 
            links: 
                - kronosaurus_maildev
                - kronosaurus_mariadb
            expose:
                - 9000
        ##
        #  NGINX
        ##
        kronosaurus_nginx:
            build: ./nginx/
            volumes_from: 
               - source_kronosaurus 
            links:
                - kronosaurus_php_fpm
            ports:
                - 8080:80
        ##
        #  Dev Email
        ##
        kronosaurus_maildev:
            image: djfarrelly/maildev
            ports:
                - "8081:80"

        ##
        #  Mysql
        ##
        kronosaurus_mariadb:
          image: mariadb
          ports:
            - "3306:3306"
          environment: 
            - MYSQL_ROOT_PASSWORD=password

        kronosaurus_phpmyadmin:
          image: phpmyadmin/phpmyadmin
          restart: always
          links:
            - kronosaurus_mariadb:db
          ports:
            - "8082:80"
          environment:
            - PMA_USER=root
            - PMA_PASSWORD=password
            - PHP_UPLOAD_MAX_FILESIZE=100MB

 
        ##
        #  Source Containers
        ##
        source_kronosaurus:
            image: nginx:stable
            volumes:
                - ./source:/var/www/html
            command: "true"